INSERT INTO currency (code, chinese_name, created_time, updated_time) VALUES
  ('USD', '美元',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('GBP', '英鎊',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('EUR', '歐元',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('TWD', '新臺幣', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('JPY', '日圓',   CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
